services:
    frontend:
        image: ghcr.io/${REPOSITORY_OWNER}/happy-memories-frontend:latest
        container_name: happy-memories-frontend
        restart: unless-stopped
        volumes:
            - happy_memories_uploads:/data/uploads:ro

    backend:
        image: ghcr.io/${REPOSITORY_OWNER}/happy-memories-backend:latest
        container_name: happy-memories-backend
        restart: unless-stopped
        environment:
            SPRING_PROFILES_ACTIVE: prod
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        volumes:
            - happy_memories_uploads:/data/uploads
        depends_on:
            - db

    db:
        image: docker.io/postgres:17-alpine
        container_name: happy-memories-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - happy_memories_db_data:/var/lib/postgresql/data

    cloudflared:
        image: docker.io/cloudflare/cloudflared:latest
        container_name: happy-memories-tunnel
        command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
        depends_on:
            - frontend
        restart: unless-stopped

volumes:
    happy_memories_uploads:
    happy_memories_db_data:
